### ISSUE TITLE
Could we get the latest master tagged as release?

### ISSUE THREAD

**Issue by disrupted** [hassio-addons/addon-unifi#131] opened 2021-01-15 14:53 UTC
# Problem/Motivation

> I am in the process of moving the Unifi Controller to this add-on. When I select my backup to restore from it tells me that it needs a newer version of the Unifi Controller software. I've seen that there are already some newer commits than the latest release tag. https://github.com/hassio-addons/addon-unifi/commit/84c65774ede0979e9e7ca38f055de24911b7bd34 

## Expected behavior

> release tag based on latest master

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> Could we get a new release with the latest Unifi controller version?

**Comment by frenck** [comment] 2021-01-15 14:53
Duplicate of other issues. Please check those for opening new ones. Thanks in advance 👍

**Closed by frenck** 2021-01-15 14:53 UTC
