### ISSUE TITLE
Unifi addon restarts when Google backups run. Access points also go to adopting status

### ISSUE THREAD

**Issue by chrisuk-web** [hassio-addons/addon-unifi#340] opened 2022-01-17 09:07 UTC
# Problem/Motivation

Access points go to adopting status when Google Backups run requiring a set-inform to be issued on each access point so that stats are available in dashboard. Also not possible to logon to addon when backups start 
![Screenshot 2022-01-17 093135](https://user-images.githubusercontent.com/81539509/149743971-663655ac-24be-42dc-981f-05c06594c23b.png)

Addon is 1.1.4, but this has happened on some previous versions. Core is core-2021.12.9,
<html>
<body>

Host Operating System | Home Assistant OS 7.1
-- | --
Update Channel | beta
Supervisor Version | supervisor-2021.12.2
Docker Version | 20.10.9
Disk Total | 109.3 GB
Disk Used | 24.7 GB
Healthy | true
Supported | true
Board | rpi4-64

</body>
</html>

## Expected behavior

Access points to not drop out. 

## Actual behavior

Access points go to adopting status when Google Backups run requiring a set-inform to be issued on each access point so that stats are available in dashboard. Add on restarts (although watch dog is set off) about a minute after backup starts. I'm not sure where old logs are stored though. New log (backup started at 0928): 

[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[09:29:28] TRACE: bashio::fs.directory_exists: /data/unifi/data
[09:29:28] TRACE: bashio::fs.directory_exists: /backup/unifi
[09:29:28] TRACE: bashio::fs.file_exists: /data/unifi/data/system.properties
[09:29:28] TRACE: bashio::fs.file_exists: /usr/lib/unifi/data/keystore
[09:29:28] TRACE: bashio::fs.file_exists: /data/keystore_reset
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:29:28] INFO: Now starting the UniFi Network Application...
[09:29:28] INFO: Note: No add-on specific logs beyond this point.
[09:29:28] TRACE: bashio::config.has_value: memory_max
[09:29:28] TRACE: bashio::config: memory_max
[09:29:28] TRACE: bashio::addon.config
[09:29:28] TRACE: bashio::cache.exists: addons.self.options.config
[09:29:28] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[09:29:28] TRACE: bashio::cache.get: addons.self.options.config
[09:29:28] TRACE: bashio::cache.exists: addons.self.options.config
[09:29:28] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[09:29:28] TRACE: bashio::jq: {"memory_max":2048,"log_level":"trace"} if (.memory_max == null) then
            null
        elif (.memory_max | type == "string") then
            .memory_max // empty
        elif (.memory_max | type == "boolean") then
            .memory_max // false
        elif (.memory_max | type == "array") then
            if (.memory_max == []) then
                empty
            else
                .memory_max[]
            end
        elif (.memory_max | type == "object") then
            if (.memory_max == {}) then
                empty
            else
                .memory_max
            end
        else
            .memory_max
        end
[09:29:29] TRACE: bashio::var.has_value: 2048
[09:29:29] TRACE: bashio::config: memory_max
[09:29:29] TRACE: bashio::addon.config
[09:29:29] TRACE: bashio::cache.exists: addons.self.options.config
[09:29:29] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[09:29:29] TRACE: bashio::cache.get: addons.self.options.config
[09:29:29] TRACE: bashio::cache.exists: addons.self.options.config
[09:29:29] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[09:29:29] TRACE: bashio::jq: {"memory_max":2048,"log_level":"trace"} if (.memory_max == null) then
            null
        elif (.memory_max | type == "string") then
            .memory_max // empty
        elif (.memory_max | type == "boolean") then
            .memory_max // false
        elif (.memory_max | type == "array") then
            if (.memory_max == []) then
                empty
            else
                .memory_max[]
            end
        elif (.memory_max | type == "object") then
            if (.memory_max == {}) then
                empty
            else
                .memory_max
            end
        else
            .memory_max
        end
[09:29:29] TRACE: bashio::config.has_value: memory_init
[09:29:29] TRACE: bashio::config: memory_init
[09:29:29] TRACE: bashio::addon.config
[09:29:29] TRACE: bashio::cache.exists: addons.self.options.config
[09:29:29] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[09:29:29] TRACE: bashio::cache.get: addons.self.options.config
[09:29:29] TRACE: bashio::cache.exists: addons.self.options.config
[09:29:29] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[09:29:29] TRACE: bashio::jq: {"memory_max":2048,"log_level":"trace"} if (.memory_init == null) then
            null
        elif (.memory_init | type == "string") then
            .memory_init // empty
        elif (.memory_init | type == "boolean") then
            .memory_init // false
        elif (.memory_init | type == "array") then
            if (.memory_init == []) then
                empty
            else
                .memory_init[]
            end
        elif (.memory_init | type == "object") then
            if (.memory_init == {}) then
                empty
            else
                .memory_init
            end
        else
            .memory_init
        end

From Home Assistant Google Drive Backup:
01-17 09:28:09 INFO Requesting a new backup
01-17 09:28:14 INFO Uploading 'Full Backup 2022-01-02 04:00:00' to Google Drive
01-17 09:38:28 INFO Backup directory changed
01-17 09:38:28 INFO Syncing Backups
01-17 09:40:57 INFO Backup finished
01-17 09:40:57 INFO Syncing Backups
01-17 09:40:58 INFO Uploading 'Full Backup 2022-01-17 09:28:08' to Google Drive

## Steps to reproduce

Run google backup

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by illwillSE** [comment] 2022-01-23 08:43
From the docs:
"During making a backup of this add-on via Home Assistant, this add-on will temporary shutdown and start up after the backup has finished. This prevents data corruption during taking the backup."

Having said that, it's also an issue for me. I have to manually readopt both my gateway and ap after each backup/restart. (set-inform ....)

**Comment by sinclairpaul** [comment] 2022-01-23 13:57
Re-Adopting issues are generally caused by not setting the inform-host in the application as per the docs.

**Comment by chrisuk-web** [comment] 2022-01-26 21:39
> From the docs: "During making a backup of this add-on via Home Assistant, this add-on will temporary shutdown and start up after the backup has finished. This prevents data corruption during taking the backup."
> 
> Having said that, it's also an issue for me. I have to manually readopt both my gateway and ap after each backup/restart. (set-inform ....)

I'm wondering if there's a way to issue a command after the backup to run the set-inform on each access point?

**Comment by sinclairpaul** [comment] 2022-01-26 22:29
Please confirm what you have set here:

![image](https://user-images.githubusercontent.com/24625998/151257869-64baa877-037b-4c48-8fab-1c25dfd0b350.png)

**Comment by chrisuk-web** [comment] 2022-01-26 22:33
Hi. It's not selected.

**Comment by sinclairpaul** [comment] 2022-01-26 22:34
Then please set it, which should resolve your issues, the address to enter will be that of your Home Assistant instance.

**Comment by chrisuk-web** [comment] 2022-01-26 22:41
Excellent - thank you. I just ran the backups manually and no need to do a set-inform manually now :-) I'm guessing this change means that they're done automatically when the addon starts again?

**Comment by sinclairpaul** [comment] 2022-01-26 22:47
It's not really the addon, I believe it is pushed as part of the config.  It is step 6.7.8 of the documentation to set this 😉, although I have created a PR to update the steps for the new UI.

I will close this out, glad you got it resolved.

**Closed by sinclairpaul** 2022-01-26 22:47 UTC

**Comment by chrisuk-web** [comment] 2022-01-26 22:54
Ok got it - thanks again Paul. Do you have the URL to that documentation please? I would like to take a look.

**Comment by chrisuk-web** [comment] 2022-01-26 23:01
Thanks @sinclairpaul

**Comment by chrisuk-web** [comment] 2022-01-26 23:04
> From the docs: "During making a backup of this add-on via Home Assistant, this add-on will temporary shutdown and start up after the backup has finished. This prevents data corruption during taking the backup."
> 
> Having said that, it's also an issue for me. I have to manually readopt both my gateway and ap after each backup/restart. (set-inform ....)

@illwillSE - see the comments from @sinclairpaul below. This has fixed it for me. To be fair it is documented in the addon documentation. I most likely lost that setting when I did a reinstall!
