### ISSUE TITLE
Controller won't start - Failed creating UniFi keystore

### ISSUE THREAD

**Issue by mizrachiran** [hassio-addons/addon-unifi#33] opened 2019-04-20 05:31 UTC
I'm running the latest hass.io version

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: HassOS 2.11  (armv7 / tinker)
 Home Assistant version: 0.91.4
 Supervisor version: 160
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] ssl.sh: executing... 
**keytool error: java.io.FileNotFoundException: /usr/lib/unifi/data/keystore (No such file or directory)
[08:27:47] FATAL: Failed creating UniFi keystore**
[cont-init.d] ssl.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment] 2019-04-20 06:04
Duplicate of https://github.com/hassio-addons/addon-unifi/issues/32.
You're still running an old version,
please update the add-on to v0.9.1 which should fix this.

**Closed** 2019-05-02 12:36 UTC
