### ISSUE TITLE
Add-on hangs on start-up after upgrade to 1.0.0 - trace log included 

### ISSUE THREAD

**Issue by craigrallen** [hassio-addons/addon-unifi#250] opened 2021-08-13 15:03 UTC
# Problem/Motivation

After upgrading, addon hangs on boot

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.8.6
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to TRACE
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[16:59:02] TRACE: bashio::fs.directory_exists: /data/unifi/data
[16:59:02] TRACE: bashio::fs.directory_exists: /backup/unifi
[16:59:02] TRACE: bashio::fs.file_exists: /data/unifi/data/system.properties
[16:59:02] TRACE: bashio::fs.file_exists: /usr/lib/unifi/data/keystore
[16:59:02] TRACE: bashio::fs.file_exists: /data/keystore_reset
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:59:02] INFO: Starting the UniFi Controller...
[16:59:02] TRACE: bashio::config.has_value: memory_max
[16:59:02] TRACE: bashio::config: memory_max
[16:59:02] TRACE: bashio::jq: /data/options.json if (.memory_max == null) then
            null
        elif (.memory_max | type == "string") then
            .memory_max // empty
        elif (.memory_max | type == "boolean") then
            .memory_max // false
        elif (.memory_max | type == "array") then
            if (.memory_max == []) then
                empty
            else
                .memory_max[]
            end
        elif (.memory_max | type == "object") then
            if (.memory_max == {}) then
                empty
            else
                .memory_max
            end
        else
            .memory_max
        end
[16:59:02] TRACE: bashio::config.has_value: memory_init
[16:59:02] TRACE: bashio::config: memory_init
[16:59:02] TRACE: bashio::jq: /data/options.json if (.memory_init == null) then
            null
        elif (.memory_init | type == "string") then
            .memory_init // empty
        elif (.memory_init | type == "boolean") then
            .memory_init // false
        elif (.memory_init | type == "array") then
            if (.memory_init == []) then
                empty
            else
                .memory_init[]
            end
        elif (.memory_init | type == "object") then
            if (.memory_init == {}) then
                empty
            else
                .memory_init
            end
        else
            .memory_init
        end

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2021-08-13 16:18
duplicate of #249

**Closed by frenck** 2021-08-13 16:18 UTC
