### ISSUE TITLE
Add-on config 'snapshot' is deprecated

### ISSUE THREAD

**Issue by rokam** [hassio-addons/addon-unifi#306] opened 2021-11-10 22:03 UTC
# Problem/Motivation

```
1-11-10 18:45:37 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
```

## Expected behavior

No Warning message

**Comment by frenck** [comment] 2021-11-10 22:05
duplicate of #263, fixed in #264

**Closed by frenck** 2021-11-10 22:05 UTC
