### ISSUE TITLE
New Controller Software 5.12.66

### ISSUE THREAD

**Issue by iamkevinv** [hassio-addons/addon-unifi#72] opened 2020-03-26 13:56 UTC
How can we get the latest controller software into the addon? Can i help? :)

**Comment by allanpersson** [comment] 2020-03-27 21:57
PR opened https://github.com/hassio-addons/addon-unifi/pull/73

**Comment by difelice** [comment] 2020-03-28 21:17
How long before this is published?

**Comment by frenck** [comment] 2020-03-28 21:19
This will happen in the upcoming days. Since the issue is resolved on dev/edge, I'll go ahead and close this "issue".

Thanks 👍

**Closed by frenck** 2020-03-28 21:19 UTC

**Comment by difelice** [comment] 2020-03-28 21:24
Thank-you!
