### ISSUE TITLE
mongod crashes constantly after backup restore

### ISSUE THREAD

**Issue by majes-github** [hassio-addons/addon-unifi#117] opened 2020-11-29 23:03 UTC
# Problem/Motivation

The add-on does not work after restoring a backup. Web UI is not working.

## Expected behavior

Add-on works.

## Actual behavior

It does not.

## Steps to reproduce

Install latest home assistant and unifi add-on. Open UI and restore a previously created backup file (*.unf)

## Proposed changes

Please upgrade MongoDB to a more recent release that does not segfault.

```
$ tail -f /usr/lib/unifi/logs/mongod.log
2020-11-30T00:03:02.634+0100 ***** SERVER RESTARTED *****
2020-11-30T00:03:02.641+0100 [initandlisten] MongoDB starting : pid=621 port=27117 dbpath=/usr/lib/unifi/data/db 32-bit host=a0d7b954-unifi
2020-11-30T00:03:02.641+0100 [initandlisten]
2020-11-30T00:03:02.641+0100 [initandlisten] ** NOTE: This is a 32 bit MongoDB binary.
2020-11-30T00:03:02.641+0100 [initandlisten] **       32 bit builds are limited to less than 2GB of data (or less with --journal).
2020-11-30T00:03:02.641+0100 [initandlisten] **       Note that journaling defaults to off for 32 bit and is currently off.
2020-11-30T00:03:02.641+0100 [initandlisten] **       See http://dochub.mongodb.org/core/32bit
2020-11-30T00:03:02.641+0100 [initandlisten]
2020-11-30T00:03:02.641+0100 [initandlisten] db version v2.6.10
2020-11-30T00:03:02.641+0100 [initandlisten] git version: nogitversion
2020-11-30T00:03:02.641+0100 [initandlisten] OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
2020-11-30T00:03:02.641+0100 [initandlisten] build info: Linux kishi10 3.2.0-84-highbank #121-Ubuntu SMP PREEMPT Tue May 5 19:44:15 UTC 2015 armv7l BOOST_LIB_VERSION=1_58
2020-11-30T00:03:02.641+0100 [initandlisten] allocator: tcmalloc
2020-11-30T00:03:02.642+0100 [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27117, unixDomainSocket: { pathPrefix: "/usr/lib/unifi/run" } }, processManagement: { pidFilePath: "/usr/lib/unifi/run/mongod.pid" }, repair: true, storage: { dbPath: "/usr/lib/unifi/data/db", smallFiles: true }, systemLog: { destination: "file", logAppend: true, path: "/usr/lib/unifi/logs/mongod.log" } }
2020-11-30T00:03:02.666+0100 [initandlisten] repairDatabase local
2020-11-30T00:03:02.667+0100 [initandlisten] allocating new ns file /usr/lib/unifi/data/db/_tmp_repairDatabase_2/local.ns, filling with zeroes...
2020-11-30T00:03:08.068+0100 [FileAllocator] allocating new datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/local.0, filling with zeroes...
2020-11-30T00:03:08.068+0100 [FileAllocator] creating directory /usr/lib/unifi/data/db/_tmp_repairDatabase_2/_tmp
2020-11-30T00:03:08.424+0100 [FileAllocator] done allocating datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/local.0, size: 16MB,  took 0.119 secs
2020-11-30T00:03:10.741+0100 [initandlisten] repairDatabase ace
2020-11-30T00:03:10.742+0100 [initandlisten] allocating new ns file /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace.ns, filling with zeroes...
2020-11-30T00:03:15.165+0100 [FileAllocator] allocating new datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace.0, filling with zeroes...
2020-11-30T00:03:15.165+0100 [FileAllocator] creating directory /usr/lib/unifi/data/db/_tmp_repairDatabase_2/_tmp
2020-11-30T00:03:15.190+0100 [FileAllocator] done allocating datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace.0, size: 16MB,  took 0.012 secs
2020-11-30T00:03:15.672+0100 [initandlisten] repairDatabase ace_stat
2020-11-30T00:03:15.673+0100 [initandlisten] allocating new ns file /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace_stat.ns, filling with zeroes...
2020-11-30T00:03:17.998+0100 [FileAllocator] allocating new datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace_stat.0, filling with zeroes...
2020-11-30T00:03:17.999+0100 [FileAllocator] creating directory /usr/lib/unifi/data/db/_tmp_repairDatabase_2/_tmp
2020-11-30T00:03:18.245+0100 [FileAllocator] done allocating datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace_stat.0, size: 16MB,  took 0.121 secs
2020-11-30T00:03:18.309+0100 [FileAllocator] allocating new datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace_stat.1, filling with zeroes...
2020-11-30T00:03:18.422+0100 [FileAllocator] done allocating datafile /usr/lib/unifi/data/db/_tmp_repairDatabase_2/ace_stat.1, size: 32MB,  took 0.112 secs
2020-11-30T00:03:18.520+0100 [initandlisten] warning Listener::getElapsedTimeMillis returning 0ms
2020-11-30T00:03:22.585+0100 [initandlisten] finished checking dbs
2020-11-30T00:03:22.585+0100 [initandlisten] dbexit:
2020-11-30T00:03:22.585+0100 [initandlisten] shutdown: going to close listening sockets...
2020-11-30T00:03:22.585+0100 [initandlisten] shutdown: going to flush diaglog...
2020-11-30T00:03:22.585+0100 [initandlisten] shutdown: going to close sockets...
2020-11-30T00:03:22.585+0100 [initandlisten] shutdown: waiting for fs preallocator...
2020-11-30T00:03:22.585+0100 [initandlisten] shutdown: closing all files...
2020-11-30T00:03:22.585+0100 [initandlisten] closeAllFiles() finished
2020-11-30T00:03:22.585+0100 [initandlisten] shutdown: removing fs lock...
2020-11-30T00:03:22.585+0100 [initandlisten] dbexit: really exiting now
2020-11-30T00:03:22.681+0100 ***** SERVER RESTARTED *****
2020-11-30T00:03:22.689+0100 [initandlisten] MongoDB starting : pid=627 port=27117 dbpath=/usr/lib/unifi/data/db 32-bit host=a0d7b954-unifi
2020-11-30T00:03:22.689+0100 [initandlisten]
2020-11-30T00:03:22.689+0100 [initandlisten] ** NOTE: This is a 32 bit MongoDB binary.
2020-11-30T00:03:22.689+0100 [initandlisten] **       32 bit builds are limited to less than 2GB of data (or less with --journal).
2020-11-30T00:03:22.689+0100 [initandlisten] **       Note that journaling defaults to off for 32 bit and is currently off.
2020-11-30T00:03:22.689+0100 [initandlisten] **       See http://dochub.mongodb.org/core/32bit
2020-11-30T00:03:22.689+0100 [initandlisten]
2020-11-30T00:03:22.689+0100 [initandlisten] db version v2.6.10
2020-11-30T00:03:22.689+0100 [initandlisten] git version: nogitversion
2020-11-30T00:03:22.689+0100 [initandlisten] OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
2020-11-30T00:03:22.689+0100 [initandlisten] build info: Linux kishi10 3.2.0-84-highbank #121-Ubuntu SMP PREEMPT Tue May 5 19:44:15 UTC 2015 armv7l BOOST_LIB_VERSION=1_58
2020-11-30T00:03:22.689+0100 [initandlisten] allocator: tcmalloc
2020-11-30T00:03:22.689+0100 [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27117, unixDomainSocket: { pathPrefix: "/usr/lib/unifi/run" } }, processManagement: { pidFilePath: "/usr/lib/unifi/run/mongod.pid" }, storage: { dbPath: "/usr/lib/unifi/data/db", smallFiles: true }, systemLog: { destination: "file", logAppend: true, path: "/usr/lib/unifi/logs/mongod.log" } }
2020-11-30T00:03:22.719+0100 [initandlisten] waiting for connections on port 27117
2020-11-30T00:03:23.038+0100 [initandlisten] connection accepted from 127.0.0.1:37414 #1 (1 connection now open)
2020-11-30T00:03:23.049+0100 [initandlisten] connection accepted from 127.0.0.1:37416 #2 (2 connections now open)
2020-11-30T00:03:23.624+0100 [conn2] SEVERE: Invalid access at address: 0xf9
2020-11-30T00:03:23.626+0100 [conn2] SEVERE: Got signal: 11 (Segmentation fault).
Backtrace:0x7639be 0x762f6e 0x76300a 0xb670d760 0xb66accec 0xb6f135e8 0xb6f13a3e 0xb6f0836a 0xb6f085e6 0xb6f1499c
 bin/mongod(_ZN5mongo15printStackTraceERSo+0x25) [0x7639be]
 bin/mongod() [0x762f6e]
 bin/mongod() [0x76300a]
 /lib/arm-linux-gnueabihf/libc.so.6(+0x25760) [0xb670d760]
 /usr/lib/arm-linux-gnueabihf/libunwind.so.8(_ULarm_step+0x5b) [0xb66accec]
 /usr/lib/arm-linux-gnueabihf/libtcmalloc.so.4(+0x255e8) [0xb6f135e8]
 /usr/lib/arm-linux-gnueabihf/libtcmalloc.so.4(_Z13GetStackTracePPvii+0x25) [0xb6f13a3e]
 /usr/lib/arm-linux-gnueabihf/libtcmalloc.so.4(_ZN8tcmalloc8PageHeap8GrowHeapEj+0xb9) [0xb6f0836a]
 /usr/lib/arm-linux-gnueabihf/libtcmalloc.so.4(_ZN8tcmalloc8PageHeap3NewEj+0x79) [0xb6f085e6]
 /usr/lib/arm-linux-gnueabihf/libtcmalloc.so.4(malloc+0x13b) [0xb6f1499c]
```

**Comment by frenck** [comment] 2020-11-30 07:53
Duplicate of #68

**Closed by frenck** 2020-11-30 07:53 UTC
