### ISSUE TITLE
go to blink page

### ISSUE THREAD

**Issue by diamondbarcode** [hassio-addons/addon-unifi#135] opened 2021-01-19 18:30 UTC
# Problem/Motivation

> Click on " OPEN WEB UI "

## Expected behavior

> open unifi controler

## Actual behavior

> it open tab go to " https://myhomeip:8443/ " and error " This site can’t be reached" 

## Steps to reproduce

> I use unifi dream machine pro and the latest home assistant

**Comment by sinclairpaul** [comment] 2021-01-19 18:33
Please post addon logs

**Comment by gerasimone** [comment] 2021-01-21 18:50
same issue for me, this is the log
`
[13:52:49] INFO: Starting the UniFi Controller...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f93bd92f923, pid=3271, tid=0x00007f93a7cc5700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0xa0a923]
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.3271
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid3271.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
`

**Comment by frenck** [comment] 2021-01-21 19:08
That is not so good, @gerasimone.

Would you mind sharing your system details? Maybe I have the hardware and software to go and try to reproduce it.

**Comment by diamondbarcode** [comment] 2021-01-21 19:24
Here my Log

--------------------

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.20.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.1.4
 Home Assistant Supervisor: 2021.01.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[13:23:26] FATAL: 
[13:23:26] FATAL: SSL has been enabled using the 'ssl' option,
[13:23:26] FATAL: this requires a SSL certificate file which is
[13:23:26] FATAL: configured using the 'certfile' option in the
[13:23:26] FATAL: add-on configuration.
[13:23:26] FATAL: 
[13:23:26] FATAL: Unfortunately, the file specified in the
[13:23:26] FATAL: 'certfile' option does not exists.
[13:23:26] FATAL: 
[13:23:26] FATAL: Please ensure the certificate file exists and
[13:23:26] FATAL: is placed in the '/ssl/' directory.
[13:23:26] FATAL: 
[13:23:26] FATAL: In case you don't have SSL yet, consider getting
[13:23:26] FATAL: a SSL certificate or setting the 'ssl' option
[13:23:26] FATAL: to 'false' in case you are not planning on using
[13:23:26] FATAL: SSL with this add-on.
[13:23:26] FATAL: 
[13:23:26] FATAL: Check the add-on manual for more information.
[13:23:26] FATAL: 
[cont-init.d] unifi.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by frenck** [comment] 2021-01-21 19:31
@diamondbarcode Sorry... but maybe you need to actually read the log:

```
[13:23:26] FATAL: SSL has been enabled using the 'ssl' option,
[13:23:26] FATAL: this requires a SSL certificate file which is
[13:23:26] FATAL: configured using the 'certfile' option in the
[13:23:26] FATAL: add-on configuration.
[13:23:26] FATAL:
[13:23:26] FATAL: Unfortunately, the file specified in the
[13:23:26] FATAL: 'certfile' option does not exists.
[13:23:26] FATAL:
[13:23:26] FATAL: Please ensure the certificate file exists and
[13:23:26] FATAL: is placed in the '/ssl/' directory.
[13:23:26] FATAL:
[13:23:26] FATAL: In case you don't have SSL yet, consider getting
[13:23:26] FATAL: a SSL certificate or setting the 'ssl' option
[13:23:26] FATAL: to 'false' in case you are not planning on using
[13:23:26] FATAL: SSL with this add-on.
[13:23:26] FATAL:
[13:23:26] FATAL: Check the add-on manual for more information.
[13:23:26] FATAL:
```

☝️ The reason and instructions are written in the error message.

**Comment by frenck** [comment] 2021-01-21 19:31
@gerasimone You issue is not related to this one as it appears. Could you please open an new issue with your hardware/system details (and repeat the log once again). Thanks 👍

**Comment by frenck** [comment] 2021-01-21 19:32
Closing this issue as it is a user configuration error, not a bug.

**Closed by frenck** 2021-01-21 19:32 UTC

**Comment by tjorim** [comment] 2021-01-21 19:33
@diamondbarcode The log says it all:

[13:23:26] FATAL: SSL has been enabled using the 'ssl' option,
[13:23:26] FATAL: this requires a SSL certificate file which is
[13:23:26] FATAL: configured using the 'certfile' option in the
[13:23:26] FATAL: add-on configuration.

@gerasimone Could you log your problem in a separate issue? It's unrelated to the initial post.
