### ISSUE TITLE
Request for Unifi controller 6.0.41+ addon

### ISSUE THREAD

**Issue by kostas-gr** [hassio-addons/addon-unifi#127] opened 2021-01-12 17:33 UTC
Trying to migrate my existing Unifi controller v6.0.41 to the one in my Home Assistant but a newer version is required.

Could you please create and publish a  new addon version using a Unifi controller 6.0.41 or later?

Than you in advance

**Comment by X1pheR** [comment] 2021-01-13 10:18
#125 was merged 11 days ago with the latest version .43. So I guess we can expect a release any time now. @frenck any estimate?

**Comment by frenck** [comment] 2021-01-13 10:18
Duplicate of many other, and not a bug either.

**Closed by frenck** 2021-01-13 10:18 UTC
